### ISSUE TITLE
Setting node "IN" in "Thermostat" mode cause node-red to crash

### ISSUE THREAD

**Issue by blackylion** [bkorda/node-red-contrib-zway#12]
After selecting Thermostat option in node "In" Node-red is crashing with following error message

19 Feb 22:33:07 - [red] Uncaught Exception:
19 Feb 22:33:07 - ReferenceError: payload is not defined
    at zWayItemIn.formatHomeKit (C:\Users\user\.node-red\node_modules\node-red-contrib-zway\nodes\in.js:169:37)
    at zWayItemIn.sendStateHomekitOnly (C:\Users\user\.node-red\node_modules\node-red-contrib-zway\nodes\in.js:132:22)
    at Timeout._onTimeout (C:\Users\user\.node-red\node_modules\node-red-contrib-zway\nodes\in.js:45:34)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

The same behaviour on Linux inside docker and outside docker as well.

Problem is that instead of "characteristic" codeword "payload" is used, please update. I will try to prepare pull request with fix

**Comment by blackylion** [comment]
Have fixed in pull-request #13
